name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: build for chrome
        run: pnpm zip --debug --browser chrome

      - name: build for firefox
        run: pnpm zip --debug --browser firefox

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ github.sha }}
          path: .output